import evanClarkAvatar from './images/evan-clark.jpg';
import johnDoeAvatar from './images/john-doe.jpg';
import oliverJamesAvatar from './images/oliver-james.jpg';

const inboxData = [
  {
    theme: 'novuDefault',
    title: 'Default',
    categories: ['All', 'System', 'Social', 'Test'],
    messages: [
      {
        category: 'system',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers are thrilled to introduce advanced task dependencies and conditional workflow triggers are thrilled to introduce advanced task dependencies and conditional workflow triggers are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: [],
      },
      {
        category: 'system',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'system',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'system',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: true,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'system',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: true,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'system',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: true,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'system',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: true,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: false,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: true,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: true,
        buttons: ['Main button', 'Secondary button'],
      },
      {
        category: 'social',
        title: 'New feature: conditional workflow triggers',
        text: 'We are thrilled to introduce advanced task dependencies and conditional workflow triggers',
        date: 'Sep 23, 2024',
        isRead: true,
        buttons: ['Main button', 'Secondary button'],
      },
    ],
  },
  {
    theme: 'notionDark',
    title: 'Notion dark',
    messages: [
      {
        title: 'Project Page',
        subtitle: 'commented in',
        text: 'Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts',
        date: '1h',
        isRead: false,
        authors: [
          {
            name: 'John Doe',
            avatar: johnDoeAvatar,
          },
        ],
      },
      {
        title: 'Weekly plan',
        subtitle: 'mentioned you in',
        text: 'For this week’s plan, how about adding a quick progress tracker and a notes section for any blockers?',
        date: '2h',
        isRead: false,
        authors: [
          {
            name: 'Oliver James',
            avatar: oliverJamesAvatar,
          },
          {
            name: 'Evan Clark',
            avatar: evanClarkAvatar,
          },
        ],
      },
      {
        title: 'Project Page',
        subtitle: 'commented in',
        text: 'Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts',
        date: '1h',
        isRead: false,
        authors: [
          {
            name: 'John Doe',
            avatar: johnDoeAvatar,
          },
        ],
      },
    ],
  },
  {
    theme: 'notionLight',
    title: 'Notion light',
    messages: [
      {
        title: 'Project Page',
        subtitle: 'commented in',
        text: 'Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts',
        date: '1h',
        isRead: false,
        authors: [
          {
            name: 'John Doe',
            avatar: johnDoeAvatar,
          },
        ],
      },
      {
        title: 'Weekly plan',
        subtitle: 'mentioned you in',
        text: 'For this week’s plan, how about adding a quick progress tracker and a notes section for any blockers?',
        date: '2h',
        isRead: false,
        authors: [
          {
            name: 'Oliver James',
            avatar: oliverJamesAvatar,
          },
          {
            name: 'Evan Clark',
            avatar: evanClarkAvatar,
          },
        ],
      },
      {
        title: 'Project Page',
        subtitle: 'commented in',
        text: 'Hey team! To improve clarity, I suggest adding priority labels, a recurring meeting schedule, and clearer task dependencies-thoughts',
        date: '1h',
        isRead: false,
        authors: [
          {
            name: 'John Doe',
            avatar: johnDoeAvatar,
          },
        ],
      },
    ],
  },
];

export default inboxData;
